dependencies:
- condition: jenkins.enabled
  name: jenkins
  repository: http://chartmuseum.jenkins-x.io
  version: 0.10.38
- alias: expose
  condition: expose.enabled
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.111
- alias: cleanup
  condition: cleanup.enabled
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.111
- condition: chartmuseum.enabled
  name: chartmuseum
  repository: http://chartmuseum.jenkins-x.io
  version: 1.1.5
- condition: nexus.enabled
  name: nexus
  repository: http://chartmuseum.jenkins-x.io
  version: 0.1.25
- name: heapster
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.3.2
- condition: docker-registry.enabled
  name: docker-registry
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.5.0
- alias: gcactivities
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.1.1
- alias: gcpods
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.1.1
- alias: gcpreviews
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.1.1
- alias: controllerbuild
  condition: controllerbuild.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.1.1
- alias: controllerrole
  condition: controllerrole.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.1.1
- alias: postinstalljob
  condition: postinstalljob.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.1.1
